Assets/Plugins/dogapi/config/routes.rb
# frozen_string_literal: true

require "query_redirector"
# require 'sidekiq/web'

Rails.application.routes.draw do
  mount Rswag::Api::Engine => "/api-docs"
  # mount Sidekiq::Web => '/admin/sidekiq'

  root to: "pages#index"
  get "/terms", to: "pages#terms", as: :terms
  get "/stats", to: "pages#stats", as: :stats
  get "/docs", to: "pages#docs", as: :docs
  get "/docs/api-v1", to: "pages#api_v1", as: :api_v1
  get "/docs/api-v2", to: "pages#api_v2", as: :api_v2

  namespace :api do
    # get '/facts', to: redirect(QueryRedirector.new('/api/v1/facts'))

    get "/facts", to: "v1/facts#index"

    namespace :v1 do
      resources :facts, only: :index
    end

    namespace :v2 do
      resources :facts, only: :index
      resources :breeds, only: %i[index show]
      resources :groups, only: %i[index show]
    end
  end
end

Assets/Plugins/dogapi/app/models/ahoy/event.rb
# frozen_string_literal: true

module Ahoy
  class Event < ApplicationRecord
    include Ahoy::QueryMethods

    self.table_name = "ahoy_events"

    belongs_to :visit
  end
end

Assets/Plugins/dogapi/app/models/ahoy/visit.rb
# frozen_string_literal: true

module Ahoy
  class Visit < ApplicationRecord
    self.table_name = "ahoy_visits"

    has_many :events, class_name: "Ahoy::Event"
  end
end

Assets/Plugins/dogapi/app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Assets/Plugins/dogapi/app/models/breed.rb
# frozen_string_literal: true

class Breed < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: :name, using: {tsearch: {prefix: true}}

  belongs_to :group
  has_many_attached :images

  store_accessor :life, :min, :max, prefix: true
  store_accessor :female_weight, :min, :max, prefix: true
  store_accessor :male_weight, :min, :max, prefix: true
end

Assets/Plugins/dogapi/app/models/fact.rb
# frozen_string_literal: true

class Fact < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_body, against: :body, using: {tsearch: {prefix: true}}
end

Assets/Plugins/dogapi/app/models/group.rb
# frozen_string_literal: true

class Group < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search_by_name, against: :name, using: {tsearch: {prefix: true}}

  has_many :breeds
end

Assets/Plugins/dogapi/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

Assets/Plugins/dogapi/app/controllers/api/base_controller.rb
# frozen_string_literal: true

module Api
  class BaseController < ApplicationController
  end
end

Assets/Plugins/dogapi/app/controllers/api/v1/base_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class BaseController < Api::BaseController
      after_action :track_action

      protected

      def track_action
        ahoy.track "get_facts_v1", request.path_parameters
      end
    end
  end
end

Assets/Plugins/dogapi/app/controllers/api/v1/facts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class FactsController < Api::V1::BaseController
      def index
        @facts = Fact.order("RANDOM()").limit(get_limit)
        if params[:raw] == "true"
          render plain: @facts.first.body
        else
          render json: {facts: @facts.map(&:body), success: true}
        end
      end

      private

      def get_limit
        limit = params[:number] || params[:limit]
        (limit.to_i.zero? || limit.to_i > 5) ? 1 : limit.to_i
      end
    end
  end
end

Assets/Plugins/dogapi/app/controllers/api/v2/base_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class BaseController < Api::BaseController
      include JSONAPI::Filtering
      include JSONAPI::Fetching
    end
  end
end

Assets/Plugins/dogapi/app/controllers/api/v2/breeds_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class BreedsController < Api::V2::BaseController
      include JSONAPI::Pagination

      after_action :track_action

      def index
        jsonapi_paginate(Breed.all) do |paginated|
          render jsonapi: paginated
        end
      end

      def show
        @breed = Breed.find_by(id: params.fetch(:id))

        if @breed.nil?
          head :not_found
        else
          render jsonapi: @breed
        end
      end

      private

      def jsonapi_page_size(pagination_params)
        per_page = pagination_params[:size].to_f.to_i
        per_page = 10 if per_page > 10 || per_page < 1
        per_page
      end

      protected

      def track_action
        ahoy.track "get_breeds_v2", request.path_parameters
      end
    end
  end
end

Assets/Plugins/dogapi/app/controllers/api/v2/facts_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class FactsController < Api::V2::BaseController
      after_action :track_action

      def index
        @facts = Fact.order("RANDOM()").limit(get_limit)
        render jsonapi: @facts
      end

      private

      def get_limit
        limit = params[:limit]
        (limit.to_i.zero? || limit.to_i > 5) ? 1 : limit.to_i
      end

      protected

      def track_action
        ahoy.track "get_facts_v2", request.path_parameters
      end
    end
  end
end

Assets/Plugins/dogapi/app/controllers/api/v2/groups_controller.rb
# frozen_string_literal: true

module Api
  module V2
    class GroupsController < Api::V2::BaseController
      include JSONAPI::Pagination

      after_action :track_action

      def index
        jsonapi_paginate(Group.all) do |paginated|
          render jsonapi: paginated
        end
      end

      def show
        @group = Group.find_by(id: params.fetch(:id))

        if @group.nil?
          head :not_found
        else
          render jsonapi: @group
        end
      end

      private

      def jsonapi_page_size(pagination_params)
        per_page = pagination_params[:size].to_f.to_i
        per_page = 10 if per_page > 10 || per_page < 1
        per_page
      end

      protected

      def track_action
        ahoy.track "get_groups_v2", request.path_parameters
      end
    end
  end
end

Assets/Plugins/dogapi/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

Assets/Plugins/dogapi/app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @fact = Fact.order("RANDOM()").first
  end

  def terms
  end

  def stats
  end

  def docs
  end

  def api_v1
  end

  def api_v2
  end
end

Assets/Plugins/dogapi/app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def page_title(separator = " - ")
    [content_for(:title), "Dog API by kinduff"].compact.join(separator)
  end

  def page_heading(title)
    content_for(:title) { title }
    content_tag(:h1, title)
  end
end

Assets/Plugins/dogapi/app/views/layouts/application.html.erb
<%- swagger = content_for?(:swagger) ? yield(:swagger) : nil %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <% if swagger %>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui.min.css" integrity="sha512-JArlzA682ixxKlWoGxYQxF+vHv527K1/NMnGbMxZERWr/16D7ZlPZUdq9+n5cA3TM030G57bSXYdN706FU9doQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <% end %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐶</text></svg>">

    <meta name="title" content="<%= page_title %>">
    <meta name="description" content="The Dog API provides a wealth of information on dog breeds, groups, and fun facts. Access and integrate this data into your website or application with our easy-to-use JSON API.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://dogapi.dog">
    <meta property="og:title" content="<%= page_title %>">
    <meta property="og:description" content="The Dog API provides a wealth of information on dog breeds, groups, and fun facts. Access and integrate this data into your website or application with our easy-to-use JSON API.">
    <meta property="og:image" content="<%= image_url 'social.jpg' %>">
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://dogapi.dog">
    <meta property="twitter:title" content="<%= page_title %>">
    <meta property="twitter:description" content="The Dog API provides a wealth of information on dog breeds, groups, and fun facts. Access and integrate this data into your website or application with our easy-to-use JSON API.">
    <meta property="twitter:image" content="<%= image_url 'social.jpg' %>">

    <script async src="https://cdn.splitbee.io/sb.js"></script>
    <%= javascript_include_tag :application, integrity: true %>
    <% if swagger %>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-bundle.min.js" integrity="sha512-8FFvTCXo6KgUt72SMpgMgMHoHnNUOPxndku0/mc+B98qIeEfZ6dpPDYJv6a1TRWHoEZeMQAKQzcwSmQixM9v2w==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.15.5/swagger-ui-standalone-preset.min.js" integrity="sha512-D0LLkbspjpDlVcVweqnmQGAHf4evBLmiyTVFxvh+c/vnJduLdDtSwT2rHg4q9bPXIp4MtY4r6fbutZsTjnoYZA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <% end %>
  </head>
  <body class="markdown-body">
    <header>
      <h1>🐶 Dog API <span>by kinduff</span></h1>
      <p>
        The Dog API provides dog data as a service!
      </p>
      <nav>
        <ul>
          <li><%= link_to_unless_current "Overview", root_path %></li>
          <li><%= link_to_unless_current "Stats", stats_path %></li>
          <li><%= link_to_unless_current "Terms of Use", terms_path %></li>
          <li><%= link_to_unless_current "API Docs", docs_path %></li>
          <li><%= link_to "GitHub ⧉", "https://github.com/kinduff/dogapi.dog", target: '_blank' %></li>
        </ul>
      </nav>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <p><small>Dog API by kinduff, providing Dog Data since 2016 - <%= ENV['GIT_COMMIT']&.slice(0, 7) %></small></p>
    </footer>
    <% if swagger %>
      <script>
        if (window.navigator.userAgent.indexOf("Edge") > -1) {
          console.log("Removing native Edge fetch in favor of swagger-ui's polyfill")
          window.fetch = undefined;
        }

        window.onload = function () {
          var configObject = {};

          configObject.url = "<%= swagger %>";
          configObject.dom_id = "#swagger-ui";
          configObject.docExpansion = "full";
          configObject.jsonEditor = false;
          configObject.defaultModelRendering = 'schema';
          configObject.showRequestHeaders = false;

          const ui = SwaggerUIBundle(configObject);
        }
      </script>
    <% end %>
  </body>
</html>

Assets/Plugins/dogapi/app/views/pages/api_v1.html.erb
<% page_heading "API V1 - Docs" %>
<% content_for :swagger, '/api-docs/v1/swagger.json' %>

<div id="swagger-ui"></div>

Assets/Plugins/dogapi/app/views/pages/api_v2.html.erb
<% page_heading "API V2 - Docs" %>
<% content_for :swagger, '/api-docs/v2/swagger.json' %>

<div id="swagger-ui"></div>

Assets/Plugins/dogapi/app/views/pages/docs.html.erb
<% page_heading "API Docs" %>

<h2>
  <a id="docs" href="#docs" aria-hidden="true"></a>
  API Docs
</h2>

<p>
  There are two versions of the API. The V1, which is the classic one (now deprecated), which uses a custom JSON response.
</p>

<p>
  And V2, which uses JSON API schema as its response format. This version will be widely supported and will be adding new features in the future.
</p>

<ul>
  <li><%= link_to "API V2", api_v2_path %></li>
  <li><%= link_to "API V1 (deprecated)", api_v1_path %></li>
</ul>

Assets/Plugins/dogapi/app/views/pages/index.html.erb
<h2>
  <a id="overview" href="#overview" aria-hidden="true"></a>
  Overview
</h2>

<p>
  The <strong>Dog API</strong> provides information on over 340 dog breeds, 20 breed groups, and fun facts. Our data is accurate and constantly updated. Easily integrate this information into your own website or application with our user-friendly API. Get started today and discover more about the world of dogs.
</p>

<p>
  For example:
</p>

<blockquote>
  <%= @fact&.body %>
</blockquote>

<p>
  Best of all, it's <strong>completely free to use</strong>!
</p>

<p>
  <a href="https://www.producthunt.com/posts/dog-api-2?utm_source=badge-featured&utm_medium=badge&utm_souce=badge-dog&#0045;api&#0045;2" target="_blank"><img src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=373528&theme=neutral" alt="Dog&#0032;API - JSON&#0032;API&#0032;with&#0032;information&#0032;on&#0032;dog&#0032;breeds&#0032;and&#0032;fun&#0032;facts | Product Hunt" style="width: 250px; height: 54px;" width="250" height="54" /></a>
</p>

<%= image_tag "dogs.jpg", alt: '3 pugs with glasses in front of a computer in an office, digital art' %>

<h3>FAQ</h3>

<h4>1. Where's the Slack button?</h4>
<p>I lost ownership of the Slack application due to Slack's policy. I tried to regain ownership of my own application but it was not possible.</p>

<h4>2. Why is this free?</h4>
<p>This API is widely used as an education tool, and for entertainment purposes. I've been hosting it for free for 6 years I'd like to keep it that way.</p>
<p>If you are interested in supporting this API, you can always <a href="https://www.buymeacoffee.com/kinduff" target="_blank">Buy me a coffee</a>.</p>

<h4>3. Why is V1 deprecated?</h4>
<p>The V1 version doesn't follow any kind of standard and was built to not be scalable. With V2, I'm planning to add new features including breeds, pictures, and other cool dog data.</p>

<h4>4. How can I get an API key?</h4>
<p>No need for now! I might introduce it in the future.</p>

<h4>5. Who are you?</h4>
<p>I'm <a href="https://kinduff.com" target="_blank">kinduff</a>! I love to build silly things and share them to the world. If you have built something interesting, let me know, it will inspire me to keep this service going. Send me an email at dev@dogapi.dog and I will check it out!</p>

Assets/Plugins/dogapi/app/views/pages/stats.html.erb
<% page_heading "Stats" %>
<h3>Visits per day (<%= number_with_delimiter(Ahoy::Visit.count) %> total)</h3>
<%= Rails.cache.fetch('stats/visits', expires_in: 1.hour) do  %>
  <% line_chart(Ahoy::Visit.group_by_day(:started_at, last: 30).count) %>
<% end %>
<h3>API Calls (<%= number_with_delimiter(Ahoy::Event.count) %> total)</h3>
<%= Rails.cache.fetch('stats/api', expires_in: 1.hour) do %>
  <%
    line_chart([
      { name: 'V2 Breeds', data: Ahoy::Event.where_event('get_breeds_v2').group_by_day(:time, last: 30).count },
      { name: 'V2 Groups', data: Ahoy::Event.where_event('get_groups_v2').group_by_day(:time, last: 30).count },
      { name: 'V2 Facts', data: Ahoy::Event.where_event('get_facts_v2').group_by_day(:time, last: 30).count },
      { name: 'V1 Facts', data: Ahoy::Event.where_event('get_facts_v1').group_by_day(:time, last: 30).count },
    ])
  %>
<% end %>

Assets/Plugins/dogapi/app/views/pages/terms.html.erb
<% page_heading "Terms of Use" %>

<h2>
  <a id="terms" href="#terms" aria-hidden="true"></a>
  Terms of Use
</h2>

<p>The following terms of service (the &quot;Terms&quot;) apply to your access and use of the Stratonauts Dog API (the &quot;API&quot;). By accessing or using the API, you agree to be bound by these <strong>Terms</strong>. If you do not agree to these Terms, you may not access or use the API. </p>

<ol>
  <li>
    <p>
      <strong>Scope</strong>. The API allows users to access a collection of dog facts that have been submitted by members of the public. Stratonauts does not endorse or verify the accuracy of any of the facts provided through the API.
    </p>
  </li>
  <li>
    <p>
      <strong>Use of the API</strong>. You may use the API for personal, non-commercial purposes only. You may not use the API for any unlawful or illegal purposes, or in any manner that could harm Stratonauts or its reputation. The API is rate limited to 60 requests per minute per client. If you need to exceed this limit, please contact dev@dogapi.dog to request an API key.
    </p>
  </li>
  <li>
    <p>
      <strong>Attribution</strong>. If you use the API, you must include the following attribution in a prominent location: &quot;Powered by Stratonauts Dog API&quot;.
    </p>
  </li>
  <li>
    <p>
      <strong>Changes to the API</strong>. Stratonauts reserves the right to change, modify, or discontinue the API at any time, without notice.
    </p>
  </li>
  <li>
    <p>
      <strong>Termination</strong>. Stratonauts may terminate your access to the API at any time, for any reason, and without notice.
    </p>
  </li>
  <li>
    <p>
      <strong>Disclaimer of Warranties</strong>. The API is provided &quot;as is&quot; and &quot;as available&quot;. Stratonauts makes no representations or warranties of any kind, express or implied, regarding the API or its use.
    </p>
  </li>
  <li>
    <p>
      <strong>Limitation of Liability</strong>. Stratonauts will not be liable for any damages arising from your use of the API.
    </p>
  </li>
  <li>
    <p>
      <strong>Governing Law</strong>. These Terms and your use of the API will be governed by and construed in accordance with the laws of the State of California, without giving effect to any principles of conflicts of law.
    </p>
  </li>
  <li>
    <p>
      <strong>Entire Agreement</strong>. These Terms constitute the entire agreement between you and Stratonauts with respect to the API, and supersede all prior or contemporaneous communications and proposals, whether oral or written, between you and Stratonauts.
    </p>
  </li>
  <li>
    <p>
      <strong>Contact Us</strong>. If you have any questions about these Terms, please contact us at dev@dogapi.dog.
    </p>
  </li>
</ol>